// The founding collection of Liberia Online Library.
//
// `text` points at a bundled public-domain file in data/texts and tells the
// importer how that file marks its sections. `gutenbergId` lets the server
// fetch (and cache) the full text from Project Gutenberg on demand.
// Books without either are print-only: members borrow copies and join holds.

export const COLLECTIONS = [
  {
    slug: 'liberian-african-voices',
    title: 'Liberian & African Voices',
    description:
      'Memoirs, novels and histories from Liberia and across the continent — the heart of our collection.',
  },
  {
    slug: 'read-tonight',
    title: 'Read Tonight, Free',
    description:
      'Complete texts that open instantly in our reader. No waitlist, no due date — just start.',
  },
  {
    slug: 'great-adventures',
    title: 'Great Adventures',
    description: 'Whales, time machines, desert islands and the far side of the world.',
  },
  {
    slug: 'mystery-gothic',
    title: 'Mysteries & the Gothic',
    description: 'Detectives, doubles, monsters and the long shadows of old houses.',
  },
  {
    slug: 'poetry-stage',
    title: 'Poetry & the Stage',
    description: 'Verse and drama that has been read aloud for centuries.',
  },
  {
    slug: 'young-readers',
    title: 'For Young Readers',
    description: 'Stories to read together, and stories to read under the covers.',
  },
  {
    slug: 'big-ideas',
    title: 'Big Ideas',
    description: 'Philosophy, strategy and politics that shaped how people think.',
  },
];

export const BOOKS = [
  // ── Bundled full texts ─────────────────────────────────────────────────────
  {
    title: 'Emma',
    author: 'Jane Austen',
    year: 1815,
    subjects: ['Fiction', 'Romance', 'Classics', 'Comedy of manners'],
    description:
      'Handsome, clever and rich, Emma Woodhouse is certain she knows what is best for everyone in Highbury — especially when it comes to whom they should marry. Austen’s sharpest comedy of misreading other people, and oneself.',
    text: { file: 'austen-emma.txt', split: 'chapter' },
    gutenbergId: 158,
    copies: 3,
    collections: ['read-tonight'],
  },
  {
    title: 'Persuasion',
    author: 'Jane Austen',
    year: 1817,
    subjects: ['Fiction', 'Romance', 'Classics'],
    description:
      'Eight years after she was persuaded to refuse Captain Wentworth, Anne Elliot meets him again. Austen’s last completed novel is a quiet, aching story about second chances.',
    text: { file: 'austen-persuasion.txt', split: 'chapter' },
    gutenbergId: 105,
    copies: 2,
    collections: ['read-tonight'],
  },
  {
    title: 'Sense and Sensibility',
    author: 'Jane Austen',
    year: 1811,
    subjects: ['Fiction', 'Romance', 'Classics', 'Sisters'],
    description:
      'After their father’s death leaves them with little, the Dashwood sisters — reserved Elinor and passionate Marianne — must navigate love, money and heartbreak in their own very different ways.',
    text: { file: 'austen-sense.txt', split: 'chapter' },
    gutenbergId: 161,
    copies: 3,
    collections: ['read-tonight'],
  },
  {
    title: 'Songs of Innocence and of Experience',
    author: 'William Blake',
    year: 1789,
    subjects: ['Poetry', 'Classics', 'Romanticism'],
    description:
      'Blake’s paired songs set a child’s wonder beside the world’s cruelty — “The Lamb” beside “The Tyger” — together with The Book of Thel.',
    text: { file: 'blake-poems.txt', split: 'caps', verse: true },
    copies: 2,
    collections: ['poetry-stage', 'read-tonight'],
  },
  {
    title: 'Stories to Tell to Children',
    author: 'Sara Cone Bryant',
    year: 1918,
    subjects: ['Children', 'Folklore', 'Short stories', 'Storytelling'],
    description:
      'More than fifty short tales and rhymes gathered by a master storyteller for reading aloud — from The Little Red Hen and The Gingerbread Man to fables from India and beyond.',
    text: { file: 'bryant-stories.txt', split: 'caps' },
    copies: 4,
    collections: ['young-readers', 'read-tonight'],
  },
  {
    title: 'The Adventures of Buster Bear',
    author: 'Thornton W. Burgess',
    year: 1916,
    subjects: ['Children', 'Animals', 'Nature'],
    description:
      'Buster Bear goes fishing, Little Joe Otter loses his catch, and the whole Green Forest has an opinion about it. Gentle, funny animal stories for young readers.',
    text: { file: 'burgess-busterbrown.txt', split: 'roman-line' },
    copies: 3,
    collections: ['young-readers', 'read-tonight'],
  },
  {
    title: 'Alice’s Adventures in Wonderland',
    author: 'Lewis Carroll',
    year: 1865,
    subjects: ['Fiction', 'Fantasy', 'Children', 'Classics'],
    description:
      'Alice follows a white rabbit down a hole and into a world of mad tea parties, a grinning cat and a queen who shouts “Off with her head!” The most famous nonsense ever written.',
    text: { file: 'carroll-alice.txt', split: 'chapter' },
    gutenbergId: 11,
    copies: 4,
    featured: true,
    collections: ['young-readers', 'read-tonight'],
  },
  {
    title: 'The Ball and the Cross',
    author: 'G. K. Chesterton',
    year: 1909,
    subjects: ['Fiction', 'Philosophy', 'Satire'],
    description:
      'A devout Catholic and a fiery atheist agree to settle their argument with swords — but all of modern England seems determined to stop the duel. A comic, strange novel of ideas.',
    text: { file: 'chesterton-ball.txt', split: 'roman-title' },
    copies: 1,
    collections: ['big-ideas', 'read-tonight'],
  },
  {
    title: 'The Wisdom of Father Brown',
    author: 'G. K. Chesterton',
    year: 1914,
    subjects: ['Fiction', 'Mystery', 'Detective', 'Short stories'],
    description:
      'The mild little priest with the umbrella solves twelve more crimes, relying less on clues than on his deep understanding of human sin.',
    text: { file: 'chesterton-brown.txt', split: 'roman-title' },
    copies: 2,
    collections: ['mystery-gothic', 'read-tonight'],
  },
  {
    title: 'The Man Who Was Thursday',
    author: 'G. K. Chesterton',
    year: 1908,
    subjects: ['Fiction', 'Mystery', 'Thriller', 'Philosophy'],
    description:
      'A poet-turned-detective infiltrates a council of anarchists, each named for a day of the week — and discovers that nothing, and nobody, is what it seems. Subtitled “A Nightmare.”',
    text: { file: 'chesterton-thursday.txt', split: 'chapter' },
    copies: 2,
    featured: true,
    collections: ['mystery-gothic', 'read-tonight'],
  },
  {
    title: 'The Parent’s Assistant',
    author: 'Maria Edgeworth',
    year: 1796,
    subjects: ['Children', 'Short stories', 'Moral tales'],
    description:
      'Stories written for children and the adults who read to them, including “Lazy Lawrence,” “Simple Susan” and “The Orphans.”',
    text: { file: 'edgeworth-parents.txt', split: 'caps' },
    copies: 1,
    collections: ['young-readers', 'read-tonight'],
  },
  {
    title: 'Moby-Dick',
    author: 'Herman Melville',
    year: 1851,
    subjects: ['Fiction', 'Adventure', 'Sea stories', 'Classics'],
    description:
      '“Call me Ishmael.” A sailor signs aboard the Pequod and discovers that its captain, Ahab, means to hunt down the white whale that took his leg — whatever the cost.',
    text: { file: 'melville-moby_dick.txt', split: 'chapter' },
    gutenbergId: 2701,
    copies: 3,
    featured: true,
    collections: ['great-adventures', 'read-tonight'],
  },
  {
    title: 'Paradise Lost',
    author: 'John Milton',
    year: 1667,
    subjects: ['Poetry', 'Epic', 'Religion', 'Classics'],
    description:
      'Milton’s epic of the war in heaven, the fall of Satan and the temptation of Adam and Eve — twelve books of the most ambitious poetry in English.',
    text: { file: 'milton-paradise.txt', split: 'book', verse: true },
    gutenbergId: 26,
    copies: 2,
    collections: ['poetry-stage', 'read-tonight'],
  },
  {
    title: 'Julius Caesar',
    author: 'William Shakespeare',
    year: 1599,
    subjects: ['Drama', 'Tragedy', 'History', 'Politics'],
    description:
      'Brutus joins the plot to kill Caesar for the good of Rome, and learns what a crowd can do after Mark Antony speaks. Printed here in the original First Folio spelling.',
    text: { file: 'shakespeare-caesar.txt', split: 'act', verse: true },
    copies: 3,
    collections: ['poetry-stage', 'read-tonight'],
  },
  {
    title: 'Hamlet',
    author: 'William Shakespeare',
    year: 1600,
    subjects: ['Drama', 'Tragedy', 'Classics'],
    description:
      'A ghost tells the Prince of Denmark that his father was murdered by the man who now wears the crown. What follows is the most performed tragedy in the world. First Folio spelling.',
    text: { file: 'shakespeare-hamlet.txt', split: 'act', verse: true },
    gutenbergId: 1524,
    copies: 3,
    collections: ['poetry-stage', 'read-tonight'],
  },
  {
    title: 'Macbeth',
    author: 'William Shakespeare',
    year: 1606,
    subjects: ['Drama', 'Tragedy', 'Classics', 'Supernatural'],
    description:
      'Three witches promise a Scottish general that he will be king. His wife makes sure of it. Shakespeare’s shortest, darkest tragedy. First Folio spelling.',
    text: { file: 'shakespeare-macbeth.txt', split: 'act', verse: true },
    copies: 2,
    collections: ['poetry-stage', 'mystery-gothic', 'read-tonight'],
  },
  {
    title: 'Leaves of Grass',
    author: 'Walt Whitman',
    year: 1855,
    subjects: ['Poetry', 'American literature', 'Classics'],
    description:
      'Whitman spent his whole life revising this one book: a vast, generous celebration of the self, the body, democracy and everyone in it. Includes “Song of Myself.”',
    text: { file: 'whitman-leaves.txt', split: 'bracket-book', verse: true },
    gutenbergId: 1322,
    copies: 2,
    collections: ['poetry-stage', 'read-tonight'],
  },

  // ── Liberian & African voices ──────────────────────────────────────────────
  {
    title: 'Murder in the Cassava Patch',
    author: 'Bai T. Moore',
    year: 1968,
    subjects: ['Fiction', 'Liberia', 'Mystery', 'African literature'],
    description:
      'A young woman is found dead in a cassava field and a small Liberian town wants answers. Bai T. Moore’s novella is one of the best-loved books in Liberian literature and a staple of Liberian classrooms.',
    copies: 5,
    featured: true,
    collections: ['liberian-african-voices', 'mystery-gothic'],
  },
  {
    title: 'The House at Sugar Beach',
    author: 'Helene Cooper',
    year: 2008,
    subjects: ['Memoir', 'Liberia', 'History', 'Family'],
    description:
      'A journalist remembers a privileged Monrovia childhood that ended with the 1980 coup, her family’s flight to America, and her return decades later to find the sister she left behind.',
    copies: 3,
    featured: true,
    collections: ['liberian-african-voices'],
  },
  {
    title: 'She Would Be King',
    author: 'Wayétu Moore',
    year: 2018,
    subjects: ['Fiction', 'Liberia', 'Historical fiction', 'Magical realism'],
    description:
      'Three people with extraordinary gifts meet in the early days of the Liberian settlement. A bold reimagining of the nation’s founding.',
    copies: 2,
    collections: ['liberian-african-voices'],
  },
  {
    title: 'This Child Will Be Great',
    author: 'Ellen Johnson Sirleaf',
    year: 2009,
    subjects: ['Memoir', 'Liberia', 'Politics', 'Women'],
    description:
      'The memoir of Africa’s first elected female head of state — from a Monrovia childhood through prison, exile and civil war to the presidency of Liberia.',
    copies: 2,
    collections: ['liberian-african-voices', 'big-ideas'],
  },
  {
    title: 'Mighty Be Our Powers',
    author: 'Leymah Gbowee',
    year: 2011,
    subjects: ['Memoir', 'Liberia', 'Peace', 'Women', 'Activism'],
    description:
      'How a young mother became the leader of the women’s peace movement that helped end Liberia’s civil war — the story of the Nobel Peace Prize laureate, in her own words.',
    copies: 2,
    collections: ['liberian-african-voices'],
  },
  {
    title: 'Christianity, Islam and the Negro Race',
    author: 'Edward Wilmot Blyden',
    year: 1887,
    subjects: ['Essays', 'Liberia', 'Religion', 'History', 'Pan-Africanism'],
    description:
      'Essays by the Liberian scholar and statesman often called the father of Pan-Africanism, arguing for the dignity and independent destiny of African peoples.',
    copies: 1,
    collections: ['liberian-african-voices', 'big-ideas'],
  },
  {
    title: 'Things Fall Apart',
    author: 'Chinua Achebe',
    year: 1958,
    subjects: ['Fiction', 'Nigeria', 'African literature', 'Classics'],
    description:
      'Okonkwo is a proud wrestler and farmer in an Igbo village when missionaries and colonial government arrive. The most widely read African novel of all time.',
    copies: 4,
    featured: true,
    collections: ['liberian-african-voices'],
  },
  {
    title: 'Half of a Yellow Sun',
    author: 'Chimamanda Ngozi Adichie',
    year: 2006,
    subjects: ['Fiction', 'Nigeria', 'Historical fiction', 'War'],
    description:
      'A houseboy, a professor’s lover and an English writer are swept up in the Nigerian Civil War. A sweeping, intimate novel of Biafra.',
    copies: 2,
    collections: ['liberian-african-voices'],
  },
  {
    title: 'Purple Hibiscus',
    author: 'Chimamanda Ngozi Adichie',
    year: 2003,
    subjects: ['Fiction', 'Nigeria', 'Coming of age', 'Family'],
    description:
      'Fifteen-year-old Kambili lives in fear of her devout, tyrannical father, until a visit to her aunt’s noisy, loving home shows her another way to live.',
    copies: 2,
    collections: ['liberian-african-voices'],
  },
  {
    title: 'Americanah',
    author: 'Chimamanda Ngozi Adichie',
    year: 2013,
    subjects: ['Fiction', 'Nigeria', 'Immigration', 'Romance'],
    description:
      'Ifemelu leaves Lagos for America and discovers what it means to be Black there; Obinze, her first love, ends up undocumented in London. A novel about race, belonging and going home.',
    copies: 3,
    collections: ['liberian-african-voices'],
  },
  {
    title: 'Weep Not, Child',
    author: 'Ngũgĩ wa Thiong’o',
    year: 1964,
    subjects: ['Fiction', 'Kenya', 'African literature', 'Coming of age'],
    description:
      'A Kenyan boy dreams of education while the Mau Mau uprising tears his family and village apart. Ngũgĩ’s first novel.',
    copies: 2,
    collections: ['liberian-african-voices'],
  },
  {
    title: 'The Joys of Motherhood',
    author: 'Buchi Emecheta',
    year: 1979,
    subjects: ['Fiction', 'Nigeria', 'Women', 'African literature'],
    description:
      'Nnu Ego gives everything to her children in colonial Lagos, and asks what a life of sacrifice actually returns. A searching, ironic novel about motherhood.',
    copies: 2,
    collections: ['liberian-african-voices'],
  },
  {
    title: 'Nervous Conditions',
    author: 'Tsitsi Dangarembga',
    year: 1988,
    subjects: ['Fiction', 'Zimbabwe', 'Coming of age', 'Women'],
    description:
      'Tambu is thrilled to escape the homestead for a mission school in colonial Rhodesia — but education comes with its own costs.',
    copies: 1,
    collections: ['liberian-african-voices'],
  },
  {
    title: 'So Long a Letter',
    author: 'Mariama Bâ',
    year: 1979,
    subjects: ['Fiction', 'Senegal', 'Women', 'African literature'],
    description:
      'Newly widowed, Ramatoulaye writes a long letter to her closest friend about marriage, polygamy and the women of modern Senegal.',
    copies: 2,
    collections: ['liberian-african-voices'],
  },
  {
    title: 'Aké: The Years of Childhood',
    author: 'Wole Soyinka',
    year: 1981,
    subjects: ['Memoir', 'Nigeria', 'Childhood'],
    description:
      'The Nobel laureate remembers growing up in a Yoruba parsonage compound — curious, mischievous and endlessly observant.',
    copies: 1,
    collections: ['liberian-african-voices'],
  },
  {
    title: 'Long Walk to Freedom',
    author: 'Nelson Mandela',
    year: 1994,
    subjects: ['Autobiography', 'South Africa', 'Politics', 'History'],
    description:
      'Mandela’s autobiography, from a village childhood to twenty-seven years in prison to the end of apartheid.',
    copies: 3,
    collections: ['liberian-african-voices', 'big-ideas'],
  },

  // ── Modern classics (print lending) ────────────────────────────────────────
  {
    title: 'Their Eyes Were Watching God',
    author: 'Zora Neale Hurston',
    year: 1937,
    subjects: ['Fiction', 'American literature', 'Women', 'Classics'],
    description:
      'Janie Crawford tells her friend the story of her three marriages and her long search for a love worth having.',
    copies: 2,
  },
  {
    title: 'Invisible Man',
    author: 'Ralph Ellison',
    year: 1952,
    subjects: ['Fiction', 'American literature', 'Classics'],
    description:
      'An unnamed narrator moves from the South to Harlem and finds that the world refuses to see him. A landmark American novel.',
    copies: 2,
  },
  {
    title: 'I Know Why the Caged Bird Sings',
    author: 'Maya Angelou',
    year: 1969,
    subjects: ['Memoir', 'American literature', 'Coming of age'],
    description:
      'The first of Angelou’s autobiographies: a childhood in Stamps, Arkansas, and St. Louis, and the discovery of literature as a way to survive.',
    copies: 2,
  },
  {
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    year: 1960,
    subjects: ['Fiction', 'American literature', 'Justice', 'Classics'],
    description:
      'Scout Finch watches her father defend a Black man falsely accused in a small Alabama town.',
    copies: 3,
  },
  {
    title: 'Beloved',
    author: 'Toni Morrison',
    year: 1987,
    subjects: ['Fiction', 'American literature', 'Historical fiction', 'Supernatural'],
    description:
      'Years after escaping slavery, Sethe’s home in Ohio is haunted — and then a young woman arrives calling herself Beloved.',
    copies: 2,
  },
  {
    title: 'One Hundred Years of Solitude',
    author: 'Gabriel García Márquez',
    year: 1967,
    subjects: ['Fiction', 'Magical realism', 'Colombia', 'Classics'],
    description:
      'Seven generations of the Buendía family in the town of Macondo, where the miraculous is ordinary and history keeps repeating itself.',
    copies: 2,
  },
  {
    title: 'The Old Man and the Sea',
    author: 'Ernest Hemingway',
    year: 1952,
    subjects: ['Fiction', 'Sea stories', 'Classics'],
    description:
      'An aging Cuban fisherman hooks an enormous marlin far out in the Gulf Stream, and refuses to let go.',
    copies: 2,
    collections: ['great-adventures'],
  },
  {
    title: 'Dune',
    author: 'Frank Herbert',
    year: 1965,
    subjects: ['Fiction', 'Science fiction', 'Adventure'],
    description:
      'On the desert planet Arrakis, source of the most valuable substance in the universe, young Paul Atreides becomes the center of a war for the future.',
    copies: 2,
    collections: ['great-adventures'],
  },
  {
    title: 'The Alchemist',
    author: 'Paulo Coelho',
    year: 1988,
    subjects: ['Fiction', 'Fable', 'Brazil'],
    description:
      'A shepherd boy from Andalusia travels to the Egyptian desert in search of treasure, and learns to listen to his heart.',
    copies: 3,
  },
  {
    title: 'A Brief History of Time',
    author: 'Stephen Hawking',
    year: 1988,
    subjects: ['Science', 'Physics', 'Cosmology'],
    description:
      'Black holes, the Big Bang and the nature of time, explained for readers without a physics degree.',
    copies: 2,
    collections: ['big-ideas'],
  },

  // ── Public-domain classics (read online via Project Gutenberg) ─────────────
  {
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    year: 1813,
    subjects: ['Fiction', 'Romance', 'Classics', 'Comedy of manners'],
    description:
      'Elizabeth Bennet has five sisters, a mother determined to marry them off and a strong first impression of the proud Mr. Darcy. It is wrong.',
    gutenbergId: 1342,
    copies: 3,
    featured: true,
  },
  {
    title: 'Frankenstein',
    author: 'Mary Shelley',
    year: 1818,
    subjects: ['Fiction', 'Gothic', 'Science fiction', 'Horror'],
    description:
      'A young scientist builds a living being and abandons it in horror. The creature, educated and alone, wants to know why.',
    gutenbergId: 84,
    copies: 2,
    collections: ['mystery-gothic'],
  },
  {
    title: 'Dracula',
    author: 'Bram Stoker',
    year: 1897,
    subjects: ['Fiction', 'Gothic', 'Horror', 'Vampires'],
    description:
      'Told in letters, diaries and newspaper clippings: a solicitor’s trip to Transylvania, a count who follows him home, and the friends who hunt him.',
    gutenbergId: 345,
    copies: 2,
    collections: ['mystery-gothic'],
  },
  {
    title: 'The Adventures of Sherlock Holmes',
    author: 'Arthur Conan Doyle',
    year: 1892,
    subjects: ['Fiction', 'Mystery', 'Detective', 'Short stories'],
    description:
      'Twelve cases for the world’s first consulting detective and his friend Dr. Watson, including “A Scandal in Bohemia” and “The Red-Headed League.”',
    gutenbergId: 1661,
    copies: 3,
    collections: ['mystery-gothic'],
  },
  {
    title: 'The Hound of the Baskervilles',
    author: 'Arthur Conan Doyle',
    year: 1902,
    subjects: ['Fiction', 'Mystery', 'Detective', 'Gothic'],
    description:
      'A family curse, a spectral hound on Dartmoor and a death that looks like fright. Holmes’s most famous case.',
    gutenbergId: 2852,
    copies: 2,
    collections: ['mystery-gothic'],
  },
  {
    title: 'The Picture of Dorian Gray',
    author: 'Oscar Wilde',
    year: 1890,
    subjects: ['Fiction', 'Gothic', 'Philosophy', 'Classics'],
    description:
      'A beautiful young man wishes that his portrait would age instead of him. The wish comes true.',
    gutenbergId: 174,
    copies: 2,
    collections: ['mystery-gothic'],
  },
  {
    title: 'Strange Case of Dr Jekyll and Mr Hyde',
    author: 'Robert Louis Stevenson',
    year: 1886,
    subjects: ['Fiction', 'Gothic', 'Horror', 'Novella'],
    description:
      'A London lawyer investigates the connection between his respectable friend Dr. Jekyll and the brutal Edward Hyde.',
    gutenbergId: 43,
    copies: 2,
    collections: ['mystery-gothic'],
  },
  {
    title: 'Treasure Island',
    author: 'Robert Louis Stevenson',
    year: 1883,
    subjects: ['Fiction', 'Adventure', 'Pirates', 'Young adult'],
    description:
      'Young Jim Hawkins finds a treasure map and sails with a crew that includes a charming one-legged cook named Long John Silver.',
    gutenbergId: 120,
    copies: 3,
    collections: ['great-adventures', 'young-readers'],
  },
  {
    title: 'The Time Machine',
    author: 'H. G. Wells',
    year: 1895,
    subjects: ['Fiction', 'Science fiction', 'Novella'],
    description:
      'A Victorian inventor travels to the year 802,701 and finds humanity divided into two very different species.',
    gutenbergId: 35,
    copies: 2,
    collections: ['great-adventures'],
  },
  {
    title: 'The War of the Worlds',
    author: 'H. G. Wells',
    year: 1898,
    subjects: ['Fiction', 'Science fiction', 'Invasion'],
    description: 'Martian cylinders land in the English countryside, and nothing on Earth can stop what emerges.',
    gutenbergId: 36,
    copies: 2,
    collections: ['great-adventures'],
  },
  {
    title: 'Adventures of Huckleberry Finn',
    author: 'Mark Twain',
    year: 1884,
    subjects: ['Fiction', 'Adventure', 'American literature', 'Classics'],
    description:
      'Huck fakes his own death and rafts down the Mississippi with Jim, a man escaping slavery.',
    gutenbergId: 76,
    copies: 2,
    collections: ['great-adventures'],
  },
  {
    title: 'The Adventures of Tom Sawyer',
    author: 'Mark Twain',
    year: 1876,
    subjects: ['Fiction', 'Adventure', 'Children', 'American literature'],
    description:
      'Whitewashed fences, a graveyard murder and a cave full of treasure in a small town on the Mississippi.',
    gutenbergId: 74,
    copies: 2,
    collections: ['young-readers'],
  },
  {
    title: 'The Call of the Wild',
    author: 'Jack London',
    year: 1903,
    subjects: ['Fiction', 'Adventure', 'Animals', 'Novella'],
    description:
      'Buck, a pampered dog from California, is stolen and sold into the brutal life of a Yukon sled team.',
    gutenbergId: 215,
    copies: 2,
    collections: ['great-adventures'],
  },
  {
    title: 'Heart of Darkness',
    author: 'Joseph Conrad',
    year: 1899,
    subjects: ['Fiction', 'Colonialism', 'Novella', 'Classics'],
    description:
      'Marlow travels up the Congo River in search of the ivory trader Kurtz. Read alongside Achebe’s famous critique of it.',
    gutenbergId: 219,
    copies: 2,
  },
  {
    title: 'A Tale of Two Cities',
    author: 'Charles Dickens',
    year: 1859,
    subjects: ['Fiction', 'Historical fiction', 'French Revolution', 'Classics'],
    description: '“It was the best of times, it was the worst of times.” London, Paris and the Terror.',
    gutenbergId: 98,
    copies: 2,
  },
  {
    title: 'Great Expectations',
    author: 'Charles Dickens',
    year: 1861,
    subjects: ['Fiction', 'Coming of age', 'Classics'],
    description:
      'The orphan Pip receives a fortune from a secret benefactor and sets out to become a gentleman.',
    gutenbergId: 1400,
    copies: 2,
  },
  {
    title: 'Jane Eyre',
    author: 'Charlotte Brontë',
    year: 1847,
    subjects: ['Fiction', 'Romance', 'Gothic', 'Classics'],
    description:
      'A plain, fiercely independent governess falls in love with her employer, Mr. Rochester — whose house holds a secret.',
    gutenbergId: 1260,
    copies: 2,
  },
  {
    title: 'Wuthering Heights',
    author: 'Emily Brontë',
    year: 1847,
    subjects: ['Fiction', 'Romance', 'Gothic', 'Classics'],
    description: 'On the Yorkshire moors, the foundling Heathcliff and Catherine Earnshaw share a love that destroys two families.',
    gutenbergId: 768,
    copies: 2,
    collections: ['mystery-gothic'],
  },
  {
    title: 'Little Women',
    author: 'Louisa May Alcott',
    year: 1868,
    subjects: ['Fiction', 'Family', 'Coming of age', 'Classics'],
    description: 'Meg, Jo, Beth and Amy March grow up in New England while their father is away at war.',
    gutenbergId: 514,
    copies: 2,
    collections: ['young-readers'],
  },
  {
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    year: 1925,
    subjects: ['Fiction', 'American literature', 'Jazz Age', 'Classics'],
    description:
      'Nick Carraway rents a house next to the mysterious Jay Gatsby, whose lavish parties all seem to be for one woman across the bay.',
    gutenbergId: 64317,
    copies: 3,
    featured: true,
  },
  {
    title: 'The Metamorphosis',
    author: 'Franz Kafka',
    year: 1915,
    subjects: ['Fiction', 'Novella', 'Absurdism', 'Classics'],
    description: 'Gregor Samsa wakes up one morning transformed into a gigantic insect. His family has to decide what to do with him.',
    gutenbergId: 5200,
    copies: 2,
  },
  {
    title: 'Crime and Punishment',
    author: 'Fyodor Dostoevsky',
    year: 1866,
    subjects: ['Fiction', 'Psychological fiction', 'Russia', 'Classics'],
    description: 'A penniless former student in St. Petersburg commits a murder to prove a theory, and cannot escape what it does to him.',
    gutenbergId: 2554,
    copies: 2,
  },
  {
    title: 'War and Peace',
    author: 'Leo Tolstoy',
    year: 1869,
    subjects: ['Fiction', 'Historical fiction', 'Russia', 'Napoleonic Wars'],
    description: 'Five aristocratic families live through Napoleon’s invasion of Russia. Enormous, and enormously alive.',
    gutenbergId: 2600,
    copies: 1,
  },
  {
    title: 'Anna Karenina',
    author: 'Leo Tolstoy',
    year: 1878,
    subjects: ['Fiction', 'Romance', 'Russia', 'Classics'],
    description: '“Happy families are all alike.” A married woman’s affair with a cavalry officer, and a landowner’s search for meaning.',
    gutenbergId: 1399,
    copies: 2,
  },
  {
    title: 'Don Quixote',
    author: 'Miguel de Cervantes',
    year: 1605,
    subjects: ['Fiction', 'Satire', 'Spain', 'Classics'],
    description: 'A man who has read too many chivalric romances becomes a knight-errant, with the practical Sancho Panza at his side.',
    gutenbergId: 996,
    copies: 1,
    collections: ['great-adventures'],
  },
  {
    title: 'The Count of Monte Cristo',
    author: 'Alexandre Dumas',
    year: 1844,
    subjects: ['Fiction', 'Adventure', 'Revenge', 'Classics'],
    description: 'Betrayed and imprisoned for fourteen years, Edmond Dantès escapes, finds a fortune and returns to settle every account.',
    gutenbergId: 1184,
    copies: 2,
    collections: ['great-adventures'],
  },
  {
    title: 'Les Misérables',
    author: 'Victor Hugo',
    year: 1862,
    subjects: ['Fiction', 'Historical fiction', 'France', 'Justice'],
    description: 'The ex-convict Jean Valjean tries to live an honest life while Inspector Javert hunts him across two decades of French history.',
    gutenbergId: 135,
    copies: 1,
  },
  {
    title: 'The Odyssey',
    author: 'Homer',
    year: -700,
    subjects: ['Poetry', 'Epic', 'Mythology', 'Classics'],
    description: 'After the fall of Troy, Odysseus spends ten years trying to get home to Ithaca.',
    gutenbergId: 1727,
    copies: 2,
    collections: ['great-adventures', 'poetry-stage'],
  },
  {
    title: 'Gulliver’s Travels',
    author: 'Jonathan Swift',
    year: 1726,
    subjects: ['Fiction', 'Satire', 'Adventure', 'Classics'],
    description: 'A ship’s surgeon washes up among tiny people, giants, a flying island and horses wiser than men.',
    gutenbergId: 829,
    copies: 2,
    collections: ['great-adventures'],
  },
  {
    title: 'Robinson Crusoe',
    author: 'Daniel Defoe',
    year: 1719,
    subjects: ['Fiction', 'Adventure', 'Survival', 'Classics'],
    description: 'Shipwrecked on an island, a sailor survives alone for twenty-eight years.',
    gutenbergId: 521,
    copies: 2,
    collections: ['great-adventures'],
  },
  {
    title: 'The Jungle Book',
    author: 'Rudyard Kipling',
    year: 1894,
    subjects: ['Fiction', 'Children', 'Animals', 'Short stories'],
    description: 'Mowgli, raised by wolves, learns the Law of the Jungle from Baloo and Bagheera.',
    gutenbergId: 236,
    copies: 2,
    collections: ['young-readers'],
  },
  {
    title: 'The Wonderful Wizard of Oz',
    author: 'L. Frank Baum',
    year: 1900,
    subjects: ['Fiction', 'Fantasy', 'Children'],
    description: 'A cyclone carries Dorothy from Kansas to Oz, where she follows the yellow brick road to find a way home.',
    gutenbergId: 55,
    copies: 2,
    collections: ['young-readers'],
  },
  {
    title: 'Peter Pan',
    author: 'J. M. Barrie',
    year: 1911,
    subjects: ['Fiction', 'Fantasy', 'Children'],
    description: 'The boy who won’t grow up takes Wendy and her brothers to Neverland.',
    gutenbergId: 16,
    copies: 2,
    collections: ['young-readers'],
  },
  {
    title: 'Anne of Green Gables',
    author: 'L. M. Montgomery',
    year: 1908,
    subjects: ['Fiction', 'Children', 'Coming of age'],
    description: 'An elderly brother and sister on Prince Edward Island send for an orphan boy, and get talkative, red-haired Anne instead.',
    gutenbergId: 45,
    copies: 2,
    collections: ['young-readers'],
  },
  {
    title: 'The Secret Garden',
    author: 'Frances Hodgson Burnett',
    year: 1911,
    subjects: ['Fiction', 'Children', 'Nature'],
    description: 'A lonely, sour girl sent to live on the Yorkshire moors discovers a locked garden, and brings it back to life.',
    gutenbergId: 113,
    copies: 2,
    collections: ['young-readers'],
  },
  {
    title: 'The Prince',
    author: 'Niccolò Machiavelli',
    year: 1532,
    subjects: ['Philosophy', 'Politics', 'Classics'],
    description: 'A notorious handbook on how to gain power and keep it.',
    gutenbergId: 1232,
    copies: 2,
    collections: ['big-ideas'],
  },
  {
    title: 'The Art of War',
    author: 'Sun Tzu',
    year: -500,
    subjects: ['Philosophy', 'Strategy', 'Military'],
    description: 'Thirteen short chapters on strategy that are still read by generals, athletes and business leaders.',
    gutenbergId: 132,
    copies: 2,
    collections: ['big-ideas'],
  },
  {
    title: 'Walden',
    author: 'Henry David Thoreau',
    year: 1854,
    subjects: ['Nonfiction', 'Philosophy', 'Nature', 'Essays'],
    description: 'Two years alone in a cabin by a Massachusetts pond, and what they taught about living deliberately.',
    gutenbergId: 205,
    copies: 1,
    collections: ['big-ideas'],
  },
  {
    title: 'Meditations',
    author: 'Marcus Aurelius',
    year: 180,
    subjects: ['Philosophy', 'Stoicism', 'Classics'],
    description: 'Private notes a Roman emperor wrote to himself about duty, loss and keeping calm.',
    gutenbergId: 2680,
    copies: 2,
    collections: ['big-ideas'],
  },
  {
    title: 'Narrative of the Life of Frederick Douglass',
    author: 'Frederick Douglass',
    year: 1845,
    subjects: ['Autobiography', 'Slavery', 'American history'],
    description: 'Douglass’s account of his enslavement in Maryland, of teaching himself to read, and of his escape to freedom.',
    gutenbergId: 23,
    copies: 2,
    collections: ['big-ideas'],
  },
  {
    title: 'The Souls of Black Folk',
    author: 'W. E. B. Du Bois',
    year: 1903,
    subjects: ['Essays', 'Sociology', 'American history', 'Race'],
    description: 'Du Bois’s essays on “double consciousness” and the color line, and on the spirituals he called the sorrow songs.',
    gutenbergId: 408,
    copies: 2,
    collections: ['big-ideas'],
  },
];
